user = User.where(email: "test@example.com").first_or_create(password: "password", password_confirmation: "password", first_name: "testing", last_name: "testing" , birthday: "1992-04-04")
pasta = [
    {
    name_of_pasta: 'Spaghetti',
    protein: 'beef & pork mince',
    sauce: 'Bolognese',
    beverage: 'red sauvignon blanc',
    cheese: 'parm',
    recipe_link: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/classic-bolognese-65a0ab3.jpg?quality=90&webp=true&resize=440,400' ,
    },
    {
    name_of_pasta: 'Lasagna',
    protein: 'vegetarian',
    sauce: 'pesto',
    beverage: 'michelob ultra',
    cheese: 'parm',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/easy-pesto-lasagne',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/pesto-6a5e8ab.jpg?quality=90&webp=true&resize=440,400' 
    },
    { 
    name_of_pasta: 'Fussili',
    protein: 'sausage',
    sauce: 'tomato',
    beverage: 'chocolate milk',
    cheese: 'asiago',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/saucy-sausage-pasta-0',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-560464_10-a602e6d.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Fussili',
    protein: 'salmon',
    sauce: 'crem fresh',
    beverage: 'coffee',
    cheese: 'parm',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/pasta-salmon-peas',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/salmonpasta-11bb3f0.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Penne',
    protein: 'salmon',
    sauce: 'white',
    beverage: 'chocolate milk',
    cheese: 'cheddar',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/italian-broccoli-salmon-bake',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-227467_12-0d8623c.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Pappardelle',
    protein: 'beef',
    sauce: 'mushroom',
    beverage: 'c',
    cheese: 'none',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/beef-stroganoff-herby-pasta',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-52759_11-bf250b1.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Spaghetti',
    protein: 'ham',
    sauce: 'white mushroom',
    beverage: 'coke',
    cheese: 'goat cheese',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/creamy-ham-leek-mushroom-spaghetti',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-327851_12-fe9f808.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Lasagna',
    protein: 'vegetarian',
    sauce: 'tomato',
    beverage: 'pepsi',
    cheese: 'mozzarella',
    recipe_link: 'https://www.bbcgoodfood.com/recipes/easy-vegetable-lasagne',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2022/02/vegetarian-lasagne-5ee6162.jpg?quality=90&webp=true&resize=440,400',
    },
    {
    name_of_pasta: 'Macaroni',
    protein: 'cheese',
    sauce: 'cheese',
    beverage: 'c',
    cheese: 'cheddar',
    recipe_link: 'https://pinchofyum.com/instant-pot-mac-and-cheese',
    image: 'https://pinchofyum.com/wp-content/uploads/Best-Instant-Pot-Mac-and-Cheese.jpg',
    },
    {
    name_of_pasta: 'Spaghetti',
    protein: 'chicken meatballs',
    sauce: 'garlic herb',
    beverage: 'water',
    cheese: 'parm',
    recipe_link: 'https://pinchofyum.com/garlic-herb-spaghetti-chicken-meatballs',
    image: 'https://pinchofyum.com/wp-content/uploads/Spaghetti-and-Meatballs-with-Noodle-Pull.jpg',
    },
    {
    name_of_pasta: 'Rigatoni',
    protein: 'sausage',
    sauce: 'white wine',
    beverage: 'c',
    cheese: 'Parm',
    recipe_link: 'https://pinchofyum.com/date-night-rigatoni',
    image: 'https://pinchofyum.com/wp-content/uploads/Date-Night-Rigatoni.jpg',
    },
    {
    name_of_pasta: 'Fettacheenee',
    protein: 'shrimp',
    sauce: 'red pepper',
    beverage: 'c',
    cheese: 'none',
    recipe_link: 'https://pinchofyum.com/red-pepper-fettuccine-shrimp',
    image: 'https://pinchofyum.com/wp-content/uploads/Red-Pepper-Fettuccine-with-Shrimp.jpg',
    },
    {
    name_of_pasta: 'Penne',
    protein: 'vegan',
    sauce: 'Vodka',
    beverage: 'vodka',
    cheese: 'none',
    recipe_link: 'https://pinchofyum.com/5-ingredient-vegan-vodka-pasta',
    image: 'https://pinchofyum.com/wp-content/uploads/Vegan-Vodka-Pasta-4.jpg',
    },
    {
    name_of_pasta: 'Penne',
    protein: 'vegan',
    sauce: 'white wine',
    beverage: 'c',
    cheese: 'nutritional yeast',
    recipe_link: 'https://www.mydarlingvegan.com/one-pot-garlic-white-wine-pasta/',
    image: 'https://www.mydarlingvegan.com/wp-content/uploads/2017/09/winepasta5.jpg',
    },
    {
    name_of_pasta: 'Ziti',
    protein: 'sausage',
    sauce: 'tomato',
    beverage: 'lemonade',
    cheese: 'mozzarella',
    recipe_link: 'https://spicysouthernkitchen.com/one-pot-ziti-with-sausage/',
    image: 'https://spicysouthernkitchen.com/wp-content/uploads/2022/02/One-Pot-Ziti-d.jpg',
    },
    {
    name_of_pasta: 'Pappardelline',
    protein: 'vegetarian',
    sauce: 'cream',
    beverage: 'c',
    cheese: 'ricotta',
    recipe_link: 'https://www.fooddolls.com/one-pot-lemon-ricotta-pasta/',
    image: 'https://www.fooddolls.com/wp-content/uploads/2021/10/Lemon-Ricotta-Pasta1123.jpg',
    },
    {
    name_of_pasta: 'Fettacheeney',
    protein: 'vegetarian',
    sauce: 'alfrado',
    beverage: 'orange juice',
    cheese: 'Parm',
    recipe_link: 'https://www.spoonforkbacon.com/one-pot-fettuccine-alfredo-recipe/',
    image: 'https://www.spoonforkbacon.com/wp-content/uploads/2020/04/fettuccine-alredo-recipe.jpg',
    },
    {
    name_of_pasta: 'Macaroni',
    protein: 'pancetta',
    sauce: 'tomato basil',
    beverage: 'hot cocoa',
    cheese: 'parm',
    recipe_link: 'https://www.cookingclassy.com/one-pot-pasta-recipe/',
    image: 'https://www.cookingclassy.com/wp-content/uploads/2021/03/one-pot-pasta-7.jpg',
    }
]
pasta.each do |each_pasta|
  user.pastas.create each_pasta
  puts "creating pasta #{each_pasta}"
end